### ISSUE TITLE
Add hyperlinks to table of contents 

### ISSUE THREAD

**Issue by dmgt** [dmgt/swc_github_flow#13]
There are many examples of how to do this in Markdown online (eg [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links)) , have yet to get it working in this document w/ GitHub Markdown

**Comment by ha0ye** [comment]
I think GitHub auto-populates html shortcut tags from th section headers. Here’s an example: https://github.com/dmgt/swc_github_flow/blob/master/for_novice_contributors.md#making-lesson-changes-with-github

**Comment by dmgt** [comment]
Added in commit [c41224](https://github.com/dmgt/swc_github_flow/commit/c41224ed621ac0e6ae8b3aec28b553c1980a2280)
