### ISSUE TITLE
git lesson page reference link not working

### ISSUE THREAD

**Issue by hoytpr** [dmgt/swc_github_flow#15]
For more details, see the Carpentry 
[git lesson reference page](http://swcarpentry.github.io/git-novice/reference/)

Gives a 404

Probably should be:
http://swcarpentry.github.io/shell-novice/reference/

**Comment by dmgt** [comment]
Good catch, thank you!
I just updated the link to http://swcarpentry.github.io/git-novice/reference.html, which has the glossary for the git lesson. Did you also want to add a link to something from the shell lesson?

**Comment by hoytpr** [comment]
You're welcome. The link you put in looks good to me.
